=== woshilmx/LRpc/LRpc-framework/LRpc-core/src/main/java/com/lmx/core/builder/xml/lrpx-configure.dtd
<!ELEMENT configuration (port, applicationname, registryAddress, IDGenerator, serialization, compress,  group,loadblance)>
        <!ELEMENT port (#PCDATA)>
        <!ELEMENT applicationname (#PCDATA)>
        <!ELEMENT registryAddress (#PCDATA)>
        <!ELEMENT IDGenerator (dataCenter, machineId)>
        <!ELEMENT dataCenter (#PCDATA)>
        <!ELEMENT machineId (#PCDATA)>
        <!ELEMENT serialization (#PCDATA)>
        <!ELEMENT compress (#PCDATA)>
        <!ELEMENT loadblance (#PCDATA)>
        <!ELEMENT group (#PCDATA)>
        <!ATTLIST loadblance class CDATA #IMPLIED>

=== woshilmx/LRpc/LRpc-domo/LRpc-provider/src/main/resources/lrpc.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE configuration SYSTEM
        "E:\javaProject2023\LRpc\LRpc-framework\LRpc-core\src\main\java\com\lmx\core\builder\xml\lrpx-configure.dtd">
<configuration>
    <!--    端口号-->
    <port>8888</port>

    <!--   应用名称 -->
    <applicationname>lrpc</applicationname>
    <!--    注册中心连接地址-->
    <registryAddress>zookeeper://114.116.233.39:2181</registryAddress>
    <!--    id生成器-->
    <IDGenerator>
        <!--       数据中心id-->
        <dataCenter>1</dataCenter>
        <!--        机器中心-->
        <machineId>2</machineId>
    </IDGenerator>
    <!--    序列化-->
    <serialization>Hessian</serialization>
    <!--    压缩的方式-->
    <compress>gzip</compress>

    <!--    负载均衡的策略-->
    <loadblance class="com.lmx.core.loadbalancer.iml.RoundLoadBalancer"></loadblance>
</configuration>
